version: "3"
services:
  db:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - clientes-compose-network
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vinicius@123
      MYSQL_DATABASE: clientes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - clientes-compose-network
    links:
      - db
    ports:
      - 5000:80

volumes:
  dbdata:

networks:
  clientes-compose-network:
    driver: bridge